merge (except for cpkg) all scripts into fpkg

diff --git a/src/fpkg b/src/fpkg
--- a/src/fpkg
+++ b/src/fpkg
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-_PKGDIR="$FPKG_ROOT/var/pkg"
+PKGDIR="$FPKG_ROOT/var/pkg"
 _GITDIR="$FPKG_ROOT/var/fpkg/git"
 _CACHEDIR="$FPKG_ROOT/var/fpkg/cache"
 _GIT_or_HTTPS="git"
@@ -20,6 +20,7 @@ if [[ -f $conf ]]; then
 	. $conf 
 	# may break fpkg if empty.
 fi
+# c:espkg
 # # # # # # # # # # # # # # #
 # May go unused temporarily #
 # # # # # # # # # # # # # # #
@@ -34,6 +35,7 @@ fi
 # # # # # # # # # # # # # # #
 # End of unused code block  #
 # # # # # # # # # # # # # # #
+# c:shapkg
 function shapkg(){
 	$_shaviagit=$(openssl dgst -sha256 -r $1.sha256)
 	$_shaviafile=$(openssl sha $1)
@@ -47,8 +49,9 @@ function shapkg(){
 	fi
 	
 }
+# c:lpkg
 function lpkg(){
-	PKGDIR="$_PKGDIR"
+	#PKGDIR="$_PKGDIR"
 	while [ ! -z "$1" ]; do
 	        pkg_version=$(qpkg "$1")
 	        if [ $? -ne 0 ]; then
@@ -61,6 +64,7 @@ function lpkg(){
 	shift
 	done
 }
+# c:rpkg
 function rpkg(){
 	DESTDIR="${FPKG_ROOT}/"
 	RC=0
@@ -94,6 +98,85 @@ function rpkg(){
 	shift
 	done
 }
+# c:ipkg
+function ipkg(){
+	#PKGDIR="$FPKG_ROOT/var/pkg"
+	DESTDIR="${FPKG_ROOT}/"
+	
+	while [ ! -z "$1" ]; do
+	        pkg_version=$(qpkg "$1")
+	        if [ $? -ne 0 ]
+	        then
+	                echo $pkg_version
+	                exit 1
+	        fi
+	
+	        cd "$DESTDIR"
+	        zstd -qcd "$PKGDIR/$1-$pkg_version.tar.zst" | tar vxf - --same-owner
+	shift
+	done
+	
+}
+# c:qpkg
+function qpkg(){
+	while [ ! -z "$1" ]; do 
+	        version=$(find $PKGDIR -regex ".*/$1-[a-z.0-9]*.tar.zst" -type f -printf "%f\n" | sort -V | tail -n 1)
+	
+	        if [ "$version" = "" ]
+	        then
+	                echo "Package not found"
+	                exit 1
+	        else
+	                version=${version##*-}
+	                version=${version%.tar.zst}
+	                echo $version
+	        fi
+	shift
+	done
+}
+# c:spkg
+function spkg(){
+	if [ "$#" -eq 0 ]; then
+	        echo "No arguments supplied."
+	        exit 0
+	fi
+	pushd
+	while [ ! -z "$1" ]; do
+	        if grep $1 "$_fpkgignore" 1>/dev/null 2>&1 ; then
+	                exit 0
+	        fi
+	        find $GITDIR -regex ".*/$1-[a-z.0-9]*.tar.zst" -type f -printf "%f\n" | sort -V | tail -n 1
+	
+	        src=$(find $GITDIR -regex ".*/$1-[a-z.0-9]*.tar.zst" -type f -printf "%f\n" | sort -V | tail -n 1)
+	
+	                case $1 in
+	                        --query) cp "$GITDIR/$src" $PKGDIR ; cp "$GITDIR/$1.d" ; qpkg "$1" ;;
+	                        *) cp "$GITDIR/$src" $PKGDIR 
+	                                if [ -f "$GITDIR/$1.d" ]; then
+	                                        cp "$GITDIR/$1.d" $PKGDIR
+	                                fi ;;
+	                esac
+	shift
+	done
+	
+}
+# c:upkg
+function upkg(){
+	DESTDIR="${FPKG_ROOT}/"
+	TEMPDIR=$(mktemp -d)  
+	
+	while [ ! -z "$1" ]; do
+	        version1=$(qpkg "$1")
+	        version2=$( PKGDIR=$TEMPDIR spkg "$1" | PKGDIR=$TEMPDIR qpkg "$1")
+	        if [ ! "$version1" = "$version2" ]; then
+	                PKGDIR="${FPKG_ROOT}/pkg" ipkg "$1"
+	        else
+	                echo "Up to date"
+	        fi
+	shift
+	done
+}
+# c:ask
 function ask() {
 	if [[ $ask == yes ]]; then
 		echo -e "You are about to $1 $2\nAre you sure? [Y/n]"
